//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksHistory
    {
        public int id { get; set; }
        public int fkTask { get; set; }
        public int fkUser { get; set; }
        public string message { get; set; }
        public int fkTaskHistoryTypes { get; set; }
        public System.DateTime dateTime { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual TasksHistoryType TasksHistoryType { get; set; }
        public virtual User User { get; set; }
    }
}
